/**
 * The vendored engine is Agent_Loop_Sim's files at the pinned commit, byte for byte, and the
 * site's fixtures were generated by the Python reference at that same commit.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import VENDORED from "@/lib/engine/vendor/VENDORED.json";

const ROOT = join(__dirname, "../..");

describe("vendored engine", () => {
  it("every file matches the SHA-256 recorded with its commit", () => {
    const files = Object.entries(VENDORED.files);
    expect(files.length).toBeGreaterThanOrEqual(15);
    expect(VENDORED.commit).toMatch(/^[0-9a-f]{40}$/);
    for (const [path, rec] of files)
      expect(
        createHash("sha256")
          .update(readFileSync(join(ROOT, path)))
          .digest("hex"),
        path,
      ).toBe(rec.sha256);
  });

  it("vendors the TS port, the tokenizer, the recorded traces and the engine's fixtures", () => {
    const froms = Object.values(VENDORED.files).map((f) => f.from);
    for (const f of [
      "ts/src/harness.ts",
      "ts/src/tokenizer.ts",
      "ts/src/engine_data.json",
      "src/agent_loop_sim/data/qwen2.5-merges.txt",
      "fixtures/engine_fixtures.json",
    ])
      expect(froms).toContain(f);
    expect(
      froms.filter((f) => f.startsWith("traces/")).length,
    ).toBeGreaterThanOrEqual(3);
  });

  it("the site's fixtures come from the same commit", () => {
    const fx = JSON.parse(
      readFileSync(join(ROOT, "tests/fixtures/site_fixtures.json"), "utf8"),
    ) as { commit: string };
    expect(fx.commit).toBe(VENDORED.commit);
  });
});
